// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkJZO3nfx_BtG75bG79_PNdFOGLDaxb0',
    appId: '1:1040896015340:web:16cfbab584c7b3bd721ec9',
    messagingSenderId: '1040896015340',
    projectId: 'future-job1',
    authDomain: 'future-job1.firebaseapp.com',
    storageBucket: 'future-job1.firebasestorage.app',
    measurementId: 'G-B425WFTBVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzl0pVsv42ImwY3qngOCgOUF9kP-xwpg',
    appId: '1:1040896015340:android:5a262ae84c37d1b9721ec9',
    messagingSenderId: '1040896015340',
    projectId: 'future-job1',
    storageBucket: 'future-job1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaclyjCOwpSzflgrk1aQhP8JqxRAFmW-Y',
    appId: '1:1040896015340:ios:0cdda943852d25de721ec9',
    messagingSenderId: '1040896015340',
    projectId: 'future-job1',
    storageBucket: 'future-job1.firebasestorage.app',
    iosBundleId: 'com.domaine.futureJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaclyjCOwpSzflgrk1aQhP8JqxRAFmW-Y',
    appId: '1:1040896015340:ios:0cdda943852d25de721ec9',
    messagingSenderId: '1040896015340',
    projectId: 'future-job1',
    storageBucket: 'future-job1.firebasestorage.app',
    iosBundleId: 'com.domaine.futureJob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkJZO3nfx_BtG75bG79_PNdFOGLDaxb0',
    appId: '1:1040896015340:web:e41d830458992e9c721ec9',
    messagingSenderId: '1040896015340',
    projectId: 'future-job1',
    authDomain: 'future-job1.firebaseapp.com',
    storageBucket: 'future-job1.firebasestorage.app',
    measurementId: 'G-M6HYDDG4T8',
  );
}
